<a href="https://colab.research.google.com/github/Sara-08671/Arreglos_12_08_2025/blob/main/Vectores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Los vectores son reserva de memoria para almacenar información, solo puede ser de un tipo, si es númerico, es númerico, si es texto, debe continuar siendo text, estp aplica para las matrices. Los arreglos son identificadores son esatticos, esto significa que es otra forma de definir, variables y constantes.

In [1]:
#Suma de vectores
import numpy as np
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
suma = vector1 + vector2
print("Suma de vectores:", suma)

#multiplicación de vectores
producto = vector1 * vector2 #Multiplicación de vectores
print("Producto de vectores:", producto)#Imprimir multiplicación

#División de vectores
división = vector1 / vector2 #División de vectores
print("División de vectores:", división) #Imprimir division

#Resta de vectores
resta = vector1 - vector2 #resta de vectores
print("Resta de vectores: ", resta)#Imprimir resta

#Potencia de vectores
potencia = vector1 **2 #Potencia de vectores
print("Potencia de vectores: ", potencia)#Imprimir potencia

Suma de vectores: [5 7 9]
Producto de vectores: [ 4 10 18]
División de vectores: [0.25 0.4  0.5 ]
Resta de vectores:  [-3 -3 -3]
Potencia de vectores:  [1 4 9]


In [2]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5])
print(vector)
# quiero imprimir el tercer elemento del vector (indice 2)
"""
Los vectores no son como las listas, no tienen un método append()
para agregar elementos y no tienen un método pop() para eliminar
elemntos, pero si tienen método reshape() para cambiar su forma,
adicionalmente despues de creado no se puede cambiar el tamaño del vector
"""
vector1 =np.zeros(5)# Creamos un vector de 5 ceros
print(vector1)
vector2 =np.ones(5)
print(vector2)
vector3 = np.random(1, 5, 100)
print(vector3)
vector4 = np.linspace(1, 10, 5)
print("linspace", vector4)
vector5 = np.random.rand(10)
print(vector5)
vector6 = np.random.randint(1, 10, 10)
print(vector6)

[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


TypeError: 'module' object is not callable